---

- name: Register acme.sh certificate information
  command: ./acme.sh --list
  args:
    chdir: "~/.acme.sh"
  changed_when: False
  register: list_domains
  become_user: "{{ acme_sh_become_user }}"

- name: List acme.sh certificate information
  debug:
    msg: "{{ list_domains.stdout_lines }}"
  when: acme_sh_list_domains and not acme_sh_uninstall
